# Generated by Django 4.1.1 on 2022-09-30 11:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceheads_options_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='about_service',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='actual_service_charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='time_for_service',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
