# Generated by Django 4.1.1 on 2022-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_link_to_official_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='guidline',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='video_tutorial',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
