# Generated by Django 4.1.1 on 2022-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_services_guidline_services_video_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='upload_form',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
