# Generated by Django 4.1.1 on 2022-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_upload_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='upload_form',
            field=models.FileField(upload_to=''),
        ),
    ]
