# Generated by Django 4.1.1 on 2022-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_services_upload_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='video_tutorial',
            field=models.CharField(max_length=100),
        ),
    ]
