# Generated by Django 4.1.1 on 2022-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_services_video_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='guidline',
            field=models.CharField(max_length=100),
        ),
    ]
