# Generated by Django 4.1.1 on 2022-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('AKSHAYA', 'AKSHAYA'), ('CSC(DIGITAL INDIA)', 'CSC(DIGITAL INDIA'), ('ONLINE SERVICE CENTER', 'ONLINE SERVICE CENTER'), ('DTP AND PHOTOSTAT SHOP', 'DTP AND PHOTOSTAT SHOP'), ('MOBILE SHOP', 'MOBILE SHOP'), ('TRAVELS', 'TRAVELS'), ('BANKING KIOSK', 'BANKING KIOSK'), ('INTERNET CAFE', 'INTERNET CAFE'), ('OTHERS', 'OTHERS')], max_length=200)),
            ],
        ),
    ]
