# Generated by Django 4.1.1 on 2022-09-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Customer Name')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='category',
            field=models.CharField(choices=[('AKSHAYA', 'AKSHAYA'), ('CSC(DIGITAL INDIA)', 'CSC(DIGITAL INDIA)'), ('ONLINE SERVICE CENTER', 'ONLINE SERVICE CENTER'), ('DTP AND PHOTOSTAT SHOP', 'DTP AND PHOTOSTAT SHOP'), ('MOBILE SHOP', 'MOBILE SHOP'), ('TRAVELS', 'TRAVELS'), ('BANKING KIOSK', 'BANKING KIOSK'), ('INTERNET CAFE', 'INTERNET CAFE'), ('OTHERS', 'OTHERS')], max_length=200),
        ),
    ]
