# Generated by Django 4.1.1 on 2022-09-30 05:51

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Importants/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
            ],
            options={
                'verbose_name_plural': 'Important Poster',
            },
        ),
        migrations.CreateModel(
            name='NewServicePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='New_Service/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
            ],
            options={
                'verbose_name_plural': 'New Service Poster',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name_plural': 'Lates News'},
        ),
    ]
