# Generated by Django 4.1.1 on 2022-10-01 09:53

from django.db import migrations, models
import django.utils.timezone
import web.functions


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_importantposter_newserviceposter_delete_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='userregistration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, default=web.functions.generate_pw, max_length=30),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.CharField(blank=True, default=web.functions.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
