# Generated by Django 4.1.1 on 2022-10-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_commonservicesposter_festivelposter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Generate Forms',
            },
        ),
    ]
