# Generated by Django 4.1.1 on 2022-10-03 06:13

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_generateforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateforms',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='Forms/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generateforms',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
