# Generated by Django 4.1.1 on 2022-10-04 09:46

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_marketingtips'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Other_Ideas/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Other Ideas',
            },
        ),
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='Documents/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='marketingtips',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='Marketing_Tip/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='softwares',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='Softwares/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='Tools/', verbose_name='Image'),
        ),
    ]
