# Generated by Django 4.1.1 on 2022-10-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("web", "0014_notes")]

    operations = [migrations.AlterModelOptions(name="order", options={"verbose_name_plural": "Orders"}), migrations.DeleteModel(name="Notes")]
