# Generated by Django 4.1.1 on 2022-10-06 05:27

from django.db import migrations, models
import web.functions


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_supportrequest_alter_userregistration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.CharField(blank=True, default=web.functions.generate_ticket_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Support Ticket',
            },
        ),
    ]
