# Generated by Django 4.1.1 on 2022-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
