# Generated by Django 4.1.1 on 2022-10-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userregistration'),
        ),
    ]
