# Generated by Django 4.1.1 on 2022-10-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
