# Generated by Django 4.1.1 on 2022-10-13 10:18

from django.db import migrations, models
import web.functions


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_userregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, default=web.functions.generate_pw, max_length=30),
        ),
    ]
